import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Alert from "@/components/common/alert";
import "../globals-landing.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Simple E-commerce | SE",
  description: "Generated by create next app",
};

export default function CustomerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Alert />
        {children}
      </body>
    </html>
  );
}
